name = "GamersReforged"
author = "Den4enko"
version = "3.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63ff95209e76470419bf63e6806c380600104f26cef232714945c8a2ce1759e1"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"
