name = "GamersReforged"
author = "Den4enko"
version = "3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bbbc9add92124ff477fd35419a8d02cc9a121f7c93df51880a252152f8e01d8"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
