name = "GamersReforged"
author = "Den4enko"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58eeeeaa660cfec6934c2e9d27cc193fcb62966c2a1973311cd141b2f0aefc25"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
