name = "GamersReforged"
author = "Den4enko"
version = "3.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad35a03c6b611b2d57c0d8d15f2c75d96b1f68749537f997997c0beb66763a47"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"
