name = "GamersReforged"
author = "Den4enko"
version = "3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c85ee6e5238abdfab3b253a0fc1b8535901c899d39ba1b4abcd7887308b6b02"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
