name = "GamersReforged"
author = "Den4enko"
version = "3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63a76fba2e4f4b0093fd3fc997261921f838dcb4ee138e7957122f0ebd5277eb"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
