name = "GamersReforged"
author = "Den4enko"
version = "3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66fa0f1e75cf4143145a26f2f8573088a3d75518e0e9e9164eed7458874d0f89"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
