name = "GamersReforged"
author = "Den4enko"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0860e7ebae0f668c6e0557183f5f1b2eefbcb56cb8bffe7153a86d86a4ddfb25"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
